# Generated by Django 4.0.5 on 2022-06-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='species',
        ),
    ]
